// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_html_sortable_table.Data;

#nullable disable

namespace dotnet_html_sortable_table.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("dotnet_html_sortable_table.Models.DemoObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IdSort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NameSort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RandIntSort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TableContainer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdSort = false,
                            NameSort = false,
                            RandIntSort = false
                        });
                });

            modelBuilder.Entity("dotnet_html_sortable_table.Models.DemoTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DemoObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RandInt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DemoObjectId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DemoObjectId = 1,
                            Name = "Bill",
                            RandInt = 3
                        },
                        new
                        {
                            Id = 2,
                            DemoObjectId = 1,
                            Name = "Bob",
                            RandInt = 9
                        },
                        new
                        {
                            Id = 3,
                            DemoObjectId = 1,
                            Name = "Jim",
                            RandInt = 0
                        });
                });

            modelBuilder.Entity("dotnet_html_sortable_table.Models.DemoTable", b =>
                {
                    b.HasOne("dotnet_html_sortable_table.Models.DemoObject", "DemoObject")
                        .WithMany("Table")
                        .HasForeignKey("DemoObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemoObject");
                });

            modelBuilder.Entity("dotnet_html_sortable_table.Models.DemoObject", b =>
                {
                    b.Navigation("Table");
                });
#pragma warning restore 612, 618
        }
    }
}
